version: "3"
services:
  db:
    image: mysql
    container_name: racedb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 13306:3306

        #app:
        #image: "asia.gcr.io/kubernetes-229910/grpc-user-service:1.0.0"
        #container_name: usersvr
        #environment:
        #- GRPC_PORT=8080
        #- DB_HOST=db
        #- DB_USER=user-users
        #- DB_PASSWORD=password
        #- DB_SCHEMA=userservice
        #ports:
        #- 8080:8080
        #links:
        #- db

